stages:
  - test

.test_template:
  stage: test
  image: docker:lastest
  services:
    - name: docker:dind
      command: ["--mtu=1300"]
  script:
    - echo "Building and running tests inside isolated container..."
    - docker build -f Dockerfile.testing -t backend-tests .
    - docker run --name test-runner -e "JwtSettings__Secret=SuperSecretTestingSigningKey12345!" -v $(pwd)/junit:/app/junit backend-tests
  artifacts:
    when: always
    paths:
      - junit/
    reports:
      junit: junit/results.xml

test:mr:
  extends: .test_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test:master:
  extends: .test_template
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
