stages:
  - test

cache:
  key:
    files:
      - "**/*.csproj"
  paths:
    - .nuget/packages/

.test_template:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:9.0
  variables:
    NUGET_PACKAGES: "$CI_PROJECT_DIR/.nuget/packages"
  before_script:
    - cd HealthcareAPI
    - dotnet restore
  script:
    - echo "Running .NET Test Suite..."
    - mkdir -p junit
    - dotnet test --no-restore --logger:"junit;LogFilePath=$CI_PROJECT_DIR/junit/results.xml"
  artifacts:
    name: "backend-test-results-$CI_COMMIT_REF_SLUG"
    when: always
    paths:
      - junit/
    reports:
      junit: junit/results.xml

test:mr:
  extends: .test_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test:master:
  extends: .test_template
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
